# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 1000

[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
# success_symbol = "[âœ](bold blue)"     # The "success_symbol" segment is being set to "âœ" with the color "bold blue"
# vimcmd_symbol = "[âœ](bold purple)"
# vimcmd_visual_symbol = "[âœ](bold purple)"
error_symbol = "[ï€](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[os]
disabled = false
style = "bold blue"

[os.symbols]
Windows = "î˜ª "
Macos = "ï£¿ "

[directory]
truncation_length = 5
disabled = false
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "

[time]
disabled = true
format = "[$time]($style)"

[username]
disabled = true
show_always = true
format = "[$user]($style) @ "

[status]
disabled = true

[hostname]
disabled = true
ssh_only = true
format = "[$hostname]($style) in "

[cmd_duration]
disabled = true
min_time = 60_0000
format = "took [$duration]($style) "

[battery]
disabled = true
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 30
style = "bold red"

[nodejs]
format = "via [ğŸ¤– $version](bold green)"

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[kubernetes]
disabled = false
format = 'on [â›µ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
detect_files = ['k8s']

[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 4
truncation_symbol = ''
ignore_branches = ['master', 'main']

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

# [git_metrics]
# disabled = false
# added_style = 'bold blue'
# format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

# [git_status]
# conflicted = 'âš”ï¸ '
# ahead = 'ğŸğŸ’¨'
# behind = 'ğŸ¢'
# diverged = 'ğŸ˜µ'
# up_to_date = 'ï€Œ'
# untracked = 'ğŸ¤·'
# stashed = 'ğŸ“¦'
# modified = 'ğŸ“'
# staged = 'ğŸ—ƒï¸'
# renamed = 'ğŸ‘…'
# deleted = 'ğŸ—‘'

# [git_status]
# conflicted = "âš”ï¸ "
# ahead = "ğŸï¸ ğŸ’¨Ã—${count}"
# behind = "ğŸ¢Ã—${count}"
# diverged = "ğŸ”± ğŸï¸ ğŸ’¨Ã—${ahead_count} ğŸ¢Ã—${behind_count}"
# up_to_date = "ï€Œ"
# untracked = "ğŸ›¤ï¸ Ã—${count}"
# stashed = 'ğŸ“¦'
# modified = "ğŸ“Ã—${count}"
# staged = "ğŸ—ƒï¸Ã—${count}"
# renamed = "ğŸ“›Ã—${count}"
# deleted = "ğŸ—‘Ã—${count}"
